apiVersion: v1
kind: Secret
metadata:
  name: leaderboard-secret
  namespace: leaderboard
type: Opaque
stringData:
  REDIS_PASSWORD: ""
  INTERNAL_API_TOKEN: ""
  MYSQL_DSN: "leaderboard:change-me@tcp(mysql:3306)/leaderboard?parseTime=true&charset=utf8mb4,utf8"
